name: Deploy to Develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Develop Environment
        run: echo "Deploying to Develop Environment..."

      - name: Delete Branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/${{ github.event.pull_request.head.ref }}" ]; then
            git push origin --delete ${{ github.event.pull_request.head.ref }}
          fi
        if: github.event.pull_request.merged == true
