name: Pull Request Checks

on:
  pull_request:
    branches: [develop, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Format the code
        working-directory: ./back-end  # Adjust this path if needed
        run: dotnet format --verbosity diagnostic --verify-no-changes

      - name: Restore dependencies
        working-directory: ./back-end  # Ensure you are in the correct directory
        run: dotnet restore --disable-parallel

      - name: Build the solution
        working-directory: ./back-end  # Ensure you are in the correct directory
        run: dotnet build --no-restore

      - name: Run all tests
        working-directory: ./back-end  # Ensure you are in the correct directory
        run: dotnet test --no-build --verbosity normal --no-restore
